/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.Color;
import java.awt.Graphics;
import java.io.Serializable;
/**
 *
 * @author Leonel
 */
public class Graficas extends javax.swing.JPanel implements Serializable{
    private int valores[] = {0,0,0};
    private String titulosX[] =  {"xTitle1", "xTitle2", "xTitle3"};
    private String titulosY[] =  {"yTitle1", "yTitle2", "yTitle3"};
    private Color color1 = Color.red;
    private Color color2 = Color.green;
    private Color color3 = Color.blue;
    private int maxY = 1;
    /**
     * Creates new form Graficas
     */
    public Graficas() {
        initComponents();
        repaint();
    }
    
    public void paint(Graphics grafico){
        super.paint(grafico);
        
        try{ 
            int alturaValor1 = valores[0] * 200 / maxY;
            int alturaValor2 = valores[1] * 200 / maxY;
            int alturaValor3 = valores[2] * 200 / maxY;

            int posy1 = 500 - alturaValor1;
            int posy2 = 500 - alturaValor2;
            int posy3 = 500 - alturaValor3;

            grafico.setColor(color1);
            grafico.fillRect(100,posy1,30,alturaValor1);
            grafico.drawString(titulosY[0],200,posy1);
            grafico.drawString(titulosX[0],100,520);

            grafico.setColor(color2);
            grafico.fillRect(200,posy2,30,alturaValor2);
            grafico.drawString(titulosY[1],200,posy2);
            grafico.drawString(titulosX[1],200,520);

            grafico.setColor(color3);
            grafico.fillRect(300,posy3,30,alturaValor3);
            grafico.drawString(titulosY[2],200,posy3);
            grafico.drawString(titulosX[2],300,520);          
        }catch(Exception e){
            System.out.println(e);
        }      
    }

    public int[] getValores() {
        return valores;
    }

    public void setValores(int[] valores) {
        this.valores = valores;
    }

    public String[] getTitulosX() {
        return titulosX;
    }

    public void setTitulosX(String[] titulosX) {
        this.titulosX = titulosX;
    }

    public String[] getTitulosY() {
        return titulosY;
    }

    public void setTitulosY(String[] titulosY) {
        this.titulosY = titulosY;
    }

    public Color getColor1() {
        return color1;
    }

    public void setColor1(Color color1) {
        this.color1 = color1;
    }

    public Color getColor2() {
        return color2;
    }

    public void setColor2(Color color2) {
        this.color2 = color2;
    }

    public Color getColor3() {
        return color3;
    }

    public void setColor3(Color color3) {
        this.color3 = color3;
    }

    public int getMaxY() {
        return maxY;
    }

    public void setMaxY(int maxY) {
        this.maxY = maxY;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 688, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 473, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
